AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for aws-lambda-cs-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  HelloGet:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloGet
      PackageType: Image
      ImageConfig:
        Command: ["HelloWorld::HelloWorld.Function::HelloGet"]
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
    Metadata:
      DockerTag: dotnet6-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: run
  HelloPost:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloPost
      PackageType: Image
      ImageConfig:
        Command: ["HelloWorld::HelloWorld.Function::HelloPost"]
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: post
    Metadata:
      DockerTag: dotnet6-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: run
  HelloPut:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloPut
      PackageType: Image
      ImageConfig:
        Command: ["HelloWorld::HelloWorld.Function::HelloPut"]
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: put
    Metadata:
      DockerTag: dotnet6-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: run
  HelloDelete:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloDelete
      PackageType: Image
      ImageConfig:
        Command: ["HelloWorld::HelloWorld.Function::HelloDelete"]
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: delete
    Metadata:
      DockerTag: dotnet6-v1
      DockerContext: ./src
      Dockerfile: Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: run

